version: '3'
services:
  web:
    build: .
    expose:
      - 5000
    volumes:
      - .:/user/src/app
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_DB=example
    networks:
      - default
    depends_on:
      - database

  redis:
    image: "redis:alpine"

  database:
    container_name: postgres
    image: "postgres:latest"
    env_file: database.conf
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
      - database-data:/var/lib/postgresql/data/
    networks:
      - default

  alembic:
    image: docker_tut_web
    volumes:
      - ./:/user/src/app
    depends_on:
      - web
    entrypoint: "alembic"

  web_nginx:
    build: ./nginx_service
    depends_on:
      - web
    ports:
      - 1337:80


volumes:
  database-data:

